name: simulation
channels:
  - defaults
dependencies:
  - absl-py=0.1.10=py36_0
  - bleach=1.5.0=py36_0
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2018.1.18=py36_0
  - cudatoolkit=8.0=3
  - cudnn=7.0.5=cuda8.0_0
  - cycler=0.10.0=py36h93f1223_0
  - dbus=1.12.2=hc3f9b76_1
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - html5lib=0.9999999=py36_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.0=hc7b2577_8
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py36h764f252_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.5.1=h6f1eeef_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.7=h26e45fe_0
  - markdown=2.6.11=py36_0
  - matplotlib=2.2.0=py36hbc4b006_0
  - mkl=2018.0.1=h19d6760_4
  - ncurses=6.0=h9df7e31_2
  - numpy=1.14.1=py36ha266831_2
  - openssl=1.0.2n=hb7f436b_0
  - pandas=0.22.0=py36hf484d3e_0
  - pcre=8.41=hc27e229_1
  - pip=9.0.1=py36_5
  - protobuf=3.5.1=py36hf484d3e_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - python=3.6.4=hc3d631a_1
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2018.3=py36_0
  - qt=5.6.2=hd25b39d_14
  - readline=7.0=ha6073c6_4
  - setuptools=38.5.1=py36_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - sqlite=3.22.0=h1bed415_0
  - tensorflow=1.5.0=0
  - tensorflow-base=1.5.0=py36hff88cb2_1
  - tensorflow-gpu=1.4.1=0
  - tensorflow-gpu-base=1.4.1=py36h01caf0a_0
  - tensorflow-tensorboard=1.5.1=py36hf484d3e_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0=py36_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.30.0=py36hfd4bba0_1
  - xz=5.2.3=h55aa19d_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - atari-py==0.1.1
    - attrs==17.4.0
    - baselines==0.1.5
    - beautifulsoup4==4.6.0
    - boto==2.48.0
    - boto3==1.6.6
    - botocore==1.9.6
    - bz2file==0.98
    - cffi==1.11.5
    - chardet==3.0.4
    - cheroot==6.0.0
    - cherrypy==14.0.0
    - click==6.7
    - cloudpickle==0.5.2
    - cython==0.27.3
    - deap==1.2.2
    - decorator==4.2.1
    - dill==0.2.7.1
    - docutils==0.14
    - docx==0.2.4
    - entrypoints==0.2.3
    - feedparser==5.2.1
    - future==0.16.0
    - gensim==3.4.0
    - glfw==1.5.1
    - gym==0.10.3
    - gym-compete==0.0.1
    - gym-recording==0.0.1
    - idna==2.6
    - imageio==2.2.0
    - ipykernel==4.8.2
    - ipython==6.2.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.1.2
    - jedi==0.11.1
    - jinja2==2.10
    - jmespath==0.9.3
    - joblib==0.11
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.2
    - jupyter-console==5.2.0
    - jupyter-core==4.4.0
    - lxml==4.1.1
    - maddpg==0.0.1
    - markupsafe==1.0
    - mesa==0.8.3
    - mistune==0.8.3
    - more-itertools==4.1.0
    - mpi4py==3.0.0
    - mujoco-py==0.5.7
    - multiagent==0.0.1
    - nbconvert==5.3.1
    - nbformat==4.4.0
    - nltk==3.2.5
    - notebook==5.4.0
    - numpy-stl==2.4.1
    - pandocfilters==1.4.2
    - parso==0.1.1
    - pattern==2.6
    - pattern3==3.0.0
    - pdfminer.six==20170720
    - pdfminer3k==1.3.1
    - pexpect==4.4.0
    - pickleshare==0.7.4
    - pillow==5.0.0
    - pluggy==0.6.0
    - ply==3.11
    - portend==2.2
    - progressbar2==3.36.0
    - prompt-toolkit==1.0.15
    - ptyprocess==0.5.2
    - py==1.5.2
    - pycparser==2.18
    - pycryptodome==3.5.1
    - pyglet==1.3.1
    - pygments==2.2.0
    - pyopengl==3.1.0
    - pytest==3.4.2
    - python-utils==2.3.0
    - pyzmq==17.0.0
    - qtconsole==4.3.1
    - requests==2.18.4
    - rllab==0.1.0
    - s3transfer==0.1.13
    - scikit-learn==0.19.1
    - scipy==1.0.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - simplejson==3.13.2
    - smart-open==1.5.6
    - tempora==1.10
    - terminado==0.8.1
    - testpath==0.3.1
    - tqdm==4.19.6
    - traitlets==4.3.2
    - urllib3==1.22
    - wcwidth==0.1.7
    - widgetsnbextension==3.1.4
    - zmq==0.0.0
prefix: /home/debbie/anaconda3/envs/simulation

